name: class_rasel
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  video_player: ^2.9.2
  chewie: ^1.8.5
  dio: ^5.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.0
  google_maps_flutter: ^2.2.5   # Latest version for Google Maps
  geolocator: ^10.1.0           # For retrieving the user's location
  permission_handler: ^11.0.1
  flutter_polyline_points: ^2.1.0
  geocoding: ^2.0.5
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adding assets
  assets:
    - assets/
    - assets/icons/
